### ISSUE TITLE
Missing files so_boot_menu.h and so_wifi_ota.h

### ISSUE THREAD

**Issue by smc8050** [decentespresso/openscale#1]
Can it be that the files `so_boot_menu.h` and `so_wifi_ota.h` used by the `2024-04-06_SofronioCoffeeRatioScale.ino` file are missing in this repository?
I have problems compiling the `.ino` file

**Comment by decentjohn** [comment]
@Sofronio can you answer?

**Comment by Sofronio** [comment]
those two files are added at version 4.2. Hope this helps.

**Comment by smc8050** [comment]
Thank you, yes now I can upload it to the ESP32.
All files complete 👍
